### ISSUE TITLE
Filter out cosmic rays that mess up fitting procedure

### ISSUE THREAD

**Issue by QingmuDeng** [Wellesley-Solar/PL_Tools#1]
![image](https://user-images.githubusercontent.com/31523537/104200715-fc024700-53f6-11eb-921a-686310a28fa2.png)

For chemistry 12 of the ML DFT project

**Comment by QingmuDeng** [comment]
![image](https://user-images.githubusercontent.com/31523537/104201495-d3c71800-53f7-11eb-9ad8-fb9b1b3c3039.png)

Additional example from the same chem

**Comment by WellesleySolar** [comment]
Resolved - turns out this minimally changed the fitting confidence
